# Generated by Django 5.1.3 on 2024-12-03 15:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='owner_profiles/', verbose_name="Owner's Profile Picture")),
                ('region', models.CharField(max_length=100, verbose_name='Region')),
                ('district', models.CharField(max_length=100, verbose_name='District')),
                ('ward', models.CharField(max_length=100, verbose_name='Ward')),
                ('street', models.CharField(max_length=100, verbose_name='Street')),
                ('house_number', models.CharField(max_length=50, verbose_name='House Number')),
                ('furnishing_status', models.CharField(choices=[('Furnished', 'Furnished'), ('Semi-Furnished', 'Semi-Furnished'), ('Unfurnished', 'Unfurnished')], default='Unfurnished', max_length=20, verbose_name='Furnishing Status')),
                ('amenities', models.JSONField(blank=True, default=dict, verbose_name='Amenities (e.g., Parking, Garden, Security)')),
                ('utilities_included', models.BooleanField(default=False, verbose_name='Utilities Included in Rent')),
                ('house_type', models.CharField(choices=[('Apartment', 'Apartment'), ('Bungalow', 'Bungalow'), ('Duplex', 'Duplex'), ('Single-Family', 'Single-Family')], default='Single-Family', max_length=50, verbose_name='House Type')),
                ('flooring_and_finishing', models.TextField(blank=True, verbose_name='Flooring and Finishing')),
                ('land_size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Land Size (sq. m)')),
                ('proximity_information', models.JSONField(blank=True, default=dict, verbose_name='Proximity Information (e.g., Schools, Hospitals)')),
                ('rules_and_restrictions', models.TextField(blank=True, null=True, verbose_name='Rules and Restrictions')),
                ('contact_information', models.TextField(verbose_name='Contact Information')),
                ('insurance_details', models.TextField(blank=True, null=True, verbose_name='Insurance Details')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='accounts.propertyowner', verbose_name='Property Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Room Number')),
                ('description', models.TextField(blank=True, verbose_name='Room Description')),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rental Price (Monthly/Yearly)')),
                ('availability_status', models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied')], default='Available', max_length=20, verbose_name='Availability Status')),
                ('room_photos', models.ImageField(upload_to='room_photos/', verbose_name='Room Photos (Upload 3)')),
                ('room_video', models.FileField(blank=True, null=True, upload_to='room_videos/', verbose_name='Room Video')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='owners.house', verbose_name='House')),
            ],
        ),
    ]
