# Generated by Django 5.1.3 on 2024-12-03 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='description',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_number',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_photos',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_video',
        ),
        migrations.AddField(
            model_name='room',
            name='photo_1',
            field=models.ImageField(default=0, upload_to='rooms/photos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='photo_2',
            field=models.ImageField(default=0, upload_to='rooms/photos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='photo_3',
            field=models.ImageField(default=0, upload_to='rooms/photos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='room_description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='video',
            field=models.FileField(default=0, upload_to='rooms/videos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='availability_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='owners.house'),
        ),
        migrations.AlterField(
            model_name='room',
            name='rental_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
