# Generated by Django 5.1.3 on 2024-12-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_remove_room_description_remove_room_room_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='photo_1',
        ),
        migrations.RemoveField(
            model_name='room',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='room',
            name='photo_3',
        ),
        migrations.AddField(
            model_name='room',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/photos/'),
        ),
        migrations.AddField(
            model_name='room',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/photos/'),
        ),
        migrations.AddField(
            model_name='room',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/photos/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='rooms/videos/'),
        ),
    ]
