# Generated by Django 5.1.3 on 2024-12-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0005_house_number_of_rooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='amenities',
            field=models.JSONField(blank=True, verbose_name='Amenities (e.g., Parking, Garden, Security)'),
        ),
    ]
