# Generated by Django 5.1.3 on 2024-12-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0006_alter_house_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='amenities',
            field=models.JSONField(blank=True, default=None, verbose_name='Amenities (e.g., Parking, Garden, Security)'),
        ),
    ]
