# Generated by Django 5.1.3 on 2024-12-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0007_alter_house_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='amenities',
            field=models.JSONField(blank=True, default=list, verbose_name='Amenities (e.g., Parking, Garden, Security)'),
        ),
        migrations.AlterField(
            model_name='house',
            name='proximity_information',
            field=models.JSONField(blank=True, default=list, verbose_name='Proximity Information (e.g., Schools, Hospitals)'),
        ),
    ]
