# Generated by Django 5.1.3 on 2024-12-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0008_alter_house_amenities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='amenities',
            field=models.TextField(blank=True, verbose_name='Amenities (e.g., Parking, Garden, Security)'),
        ),
        migrations.AlterField(
            model_name='house',
            name='proximity_information',
            field=models.TextField(blank=True, verbose_name='Proximity Information (e.g., Schools, Hospitals)'),
        ),
    ]
