# Generated by Django 5.1.3 on 2024-12-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0011_house_house_photo_1_house_house_photo_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='house_name',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='House Name'),
        ),
    ]
