# Generated by Django 5.1.3 on 2024-12-06 12:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_client_profile_picture_propertyowner_profile_picture'),
        ('owners', '0012_house_house_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('email', models.EmailField(help_text='Email address for the agent.', max_length=254, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format +255XXXXXXXXX.', regex='^\\+255\\d{9}$')], verbose_name='Phone Number')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='agent_profiles/', verbose_name='Profile Picture')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended')], default='Active', max_length=10, verbose_name='Status')),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Commission rate in percentage (e.g., 10.00 for 10%).', max_digits=5, null=True, verbose_name='Commission Rate')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_verified', models.BooleanField(default=False, help_text="Indicates whether the agent's identity has been verified.", verbose_name='Is Verified')),
                ('assigned_houses', models.ManyToManyField(blank=True, help_text='Houses managed by this agent.', related_name='agents', to='owners.house', verbose_name='Assigned Houses')),
                ('property_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='accounts.propertyowner', verbose_name='Property Owner')),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'ordering': ['-created_at'],
            },
        ),
    ]
