# Generated by Django 5.1.3 on 2024-12-07 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_client_profile_picture_propertyowner_profile_picture'),
        ('owners', '0013_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_months_to_pay', models.PositiveIntegerField(default=1, help_text='The minimum number of months a client must pay for.', verbose_name='Minimum Months to Pay')),
                ('payment_terms', models.TextField(blank=True, help_text='Terms and conditions for payment.', null=True, verbose_name='Payment Terms')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('house', models.OneToOneField(help_text='The house these booking rules apply to.', on_delete=django.db.models.deletion.CASCADE, related_name='booking_rule', to='owners.house', verbose_name='House')),
                ('owner', models.ForeignKey(help_text='The owner of the house these rules apply to.', on_delete=django.db.models.deletion.CASCADE, related_name='booking_rules', to='accounts.propertyowner', verbose_name='Property Owner')),
            ],
            options={
                'verbose_name': 'Booking Rule',
                'verbose_name_plural': 'Booking Rules',
                'ordering': ['-created_at'],
            },
        ),
    ]
