# Generated by Django 5.1.3 on 2024-12-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0014_bookingrule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingrule',
            name='house',
        ),
        migrations.AddField(
            model_name='bookingrule',
            name='houses',
            field=models.ManyToManyField(help_text='The houses these booking rules apply to.', related_name='booking_rules', to='owners.house', verbose_name='Houses'),
        ),
    ]
