# Generated by Django 5.1.3 on 2024-12-07 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0015_remove_bookingrule_house_bookingrule_houses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingrule',
            name='houses',
        ),
        migrations.AddField(
            model_name='bookingrule',
            name='house',
            field=models.ForeignKey(default=0, help_text='The house these booking rules apply to.', on_delete=django.db.models.deletion.CASCADE, related_name='booking_rules', to='owners.house', verbose_name='House'),
            preserve_default=False,
        ),
    ]
