# Generated by Django 5.1.3 on 2024-12-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0016_remove_bookingrule_houses_bookingrule_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='house_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='House Name'),
        ),
    ]
