# Generated by Django 5.1.3 on 2024-12-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0018_bookingrule_payment_method'),
        ('settings', '0004_alter_payment_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingrule',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='bookingrule',
            name='payment_methods',
            field=models.ManyToManyField(blank=True, help_text='Select one or more payment methods that will be used during booking.', related_name='booking_rules', to='settings.payment', verbose_name='Payment Methods'),
        ),
    ]
