# Generated by Django 5.1.3 on 2024-12-10 21:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_client_profile_picture_propertyowner_profile_picture'),
        ('owners', '0020_agent_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(blank=True, help_text="The content of the client's message.", null=True, verbose_name='Message Text')),
                ('audio', models.FileField(blank=True, help_text='Optional audio message file (e.g. .mp3, .wav).', null=True, upload_to='messages/audio/', verbose_name='Audio Message')),
                ('image', models.ImageField(blank=True, help_text='Optional image attachment.', null=True, upload_to='messages/images/', verbose_name='Image')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_to_agent', to='owners.agent', verbose_name='Agent')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_from_client', to='accounts.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Client Message',
                'verbose_name_plural': 'Client Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.TextField(blank=True, help_text="The content of the agent's reply.", null=True, verbose_name='Reply Text')),
                ('audio', models.FileField(blank=True, help_text='Optional audio reply (e.g. .mp3, .wav).', null=True, upload_to='replies/audio/', verbose_name='Reply Audio')),
                ('image', models.ImageField(blank=True, help_text='Optional image attachment.', null=True, upload_to='replies/images/', verbose_name='Reply Image')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies_from_agent', to='owners.agent', verbose_name='Agent')),
                ('client_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_replies', to='owners.clientmessage', verbose_name='Client Message')),
            ],
            options={
                'verbose_name': 'Agent Reply',
                'verbose_name_plural': 'Agent Replies',
                'ordering': ['-created_at'],
            },
        ),
    ]
