# Generated by Django 5.1.3 on 2024-12-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0021_clientmessage_agentreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentreply',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Indicates whether the reply has been read by the client.', verbose_name='Is Read'),
        ),
        migrations.AddField(
            model_name='clientmessage',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Indicates whether the message has been read by the agent.', verbose_name='Is Read'),
        ),
    ]
