# Generated by Django 5.1.3 on 2024-12-11 17:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0022_agentreply_is_read_clientmessage_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousePromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Words or a detailed description to promote the house or room.', null=True, verbose_name='Promotion Description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this promotion was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this promotion was last updated.', verbose_name='Last Updated')),
                ('agent', models.ForeignKey(help_text='The agent who created this promotion.', on_delete=django.db.models.deletion.CASCADE, related_name='house_promotions', to='owners.agent', verbose_name='Agent')),
                ('house', models.ForeignKey(help_text='The house that is being promoted.', on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='owners.house', verbose_name='House')),
                ('room', models.ForeignKey(blank=True, help_text='Optional: The specific room of the house being promoted. Leave blank to promote the entire house.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='owners.room', verbose_name='Room')),
            ],
            options={
                'verbose_name': 'House Promotion',
                'verbose_name_plural': 'House Promotions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', help_text='Type of media (image or video).', max_length=5, verbose_name='Media Type')),
                ('file', models.FileField(help_text='Image or video file to promote the house/room.', upload_to='promotion_media/', verbose_name='Media File')),
                ('caption', models.CharField(blank=True, help_text='Optional caption or title for the media.', max_length=255, null=True, verbose_name='Caption')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this media was uploaded.', verbose_name='Uploaded At')),
                ('promotion', models.ForeignKey(help_text='The promotion this media is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='owners.housepromotion', verbose_name='House Promotion')),
            ],
            options={
                'verbose_name': 'Promotion Media',
                'verbose_name_plural': 'Promotion Media',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
