# Generated by Django 5.1.3 on 2024-12-14 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0023_housepromotion_promotionmedia'),
        ('settings', '0009_street'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='house_photo_1',
        ),
        migrations.RemoveField(
            model_name='house',
            name='house_photo_2',
        ),
        migrations.RemoveField(
            model_name='house',
            name='house_photo_3',
        ),
        migrations.RemoveField(
            model_name='house',
            name='house_photo_4',
        ),
        migrations.RemoveField(
            model_name='house',
            name='house_photo_5',
        ),
        migrations.RemoveField(
            model_name='house',
            name='house_video',
        ),
        migrations.RemoveField(
            model_name='room',
            name='photo_1',
        ),
        migrations.RemoveField(
            model_name='room',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='room',
            name='photo_3',
        ),
        migrations.RemoveField(
            model_name='room',
            name='photo_4',
        ),
        migrations.RemoveField(
            model_name='room',
            name='photo_5',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_video',
        ),
        migrations.AlterField(
            model_name='house',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='settings.district', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='house',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='settings.region', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='house',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='settings.street', verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='house',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='settings.ward', verbose_name='Ward'),
        ),
        migrations.CreateModel(
            name='HouseMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], default='photo', max_length=5, verbose_name='Media Type')),
                ('media_file', models.FileField(upload_to='house_medias/', verbose_name='House Media File')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='owners.house', verbose_name='House')),
            ],
        ),
        migrations.CreateModel(
            name='RoomMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], default='photo', max_length=5, verbose_name='Media Type')),
                ('media_file', models.FileField(upload_to='room_medias/', verbose_name='Room Media File')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='owners.room', verbose_name='Room')),
            ],
        ),
    ]
