# Generated by Django 5.1.3 on 2024-12-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0024_remove_house_house_photo_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='allows_installment_payment',
            field=models.BooleanField(default=False, verbose_name='Allows Installment Payment?'),
        ),
        migrations.AddField(
            model_name='house',
            name='has_backup_generator',
            field=models.BooleanField(default=False, verbose_name='Has Backup Generator?'),
        ),
        migrations.AddField(
            model_name='house',
            name='has_cctv_cameras',
            field=models.BooleanField(default=False, verbose_name='Has CCTV Cameras?'),
        ),
        migrations.AddField(
            model_name='house',
            name='has_elevator',
            field=models.BooleanField(default=False, verbose_name='Has Elevator?'),
        ),
        migrations.AddField(
            model_name='house',
            name='has_entertaining_area',
            field=models.BooleanField(default=False, verbose_name='Has Entertaining Area?'),
        ),
        migrations.AddField(
            model_name='house',
            name='has_fence',
            field=models.BooleanField(default=False, verbose_name='Has Fence?'),
        ),
        migrations.AddField(
            model_name='house',
            name='has_floors',
            field=models.BooleanField(default=False, verbose_name='Has Multiple Floors?'),
        ),
        migrations.AddField(
            model_name='house',
            name='has_garden',
            field=models.BooleanField(default=False, verbose_name='Has Garden?'),
        ),
        migrations.AddField(
            model_name='house',
            name='has_grill_doors_and_windows',
            field=models.BooleanField(default=False, verbose_name='Has Grill Doors/Windows?'),
        ),
        migrations.AddField(
            model_name='house',
            name='has_historical_significance',
            field=models.BooleanField(default=False, verbose_name='Has Historical Significance?'),
        ),
        migrations.AddField(
            model_name='house',
            name='has_outdoor_seating_area',
            field=models.BooleanField(default=False, verbose_name='Has Outdoor Seating Area?'),
        ),
        migrations.AddField(
            model_name='house',
            name='has_parking',
            field=models.BooleanField(default=False, verbose_name='Has Parking?'),
        ),
        migrations.AddField(
            model_name='house',
            name='has_playground',
            field=models.BooleanField(default=False, verbose_name='Has Playground?'),
        ),
        migrations.AddField(
            model_name='house',
            name='has_rooftop_for_resting',
            field=models.BooleanField(default=False, verbose_name='Has Rooftop for Resting?'),
        ),
        migrations.AddField(
            model_name='house',
            name='has_security_guard',
            field=models.BooleanField(default=False, verbose_name='Has Security Guard?'),
        ),
        migrations.AddField(
            model_name='house',
            name='has_swimming_pool',
            field=models.BooleanField(default=False, verbose_name='Has Swimming Pool?'),
        ),
        migrations.AddField(
            model_name='house',
            name='has_water_services',
            field=models.BooleanField(default=False, verbose_name='Has Water Services?'),
        ),
        migrations.AddField(
            model_name='house',
            name='has_wifi',
            field=models.BooleanField(default=False, verbose_name='Has WiFi?'),
        ),
        migrations.AddField(
            model_name='house',
            name='is_disability_friendly',
            field=models.BooleanField(default=False, verbose_name='Is Disability Friendly?'),
        ),
        migrations.AddField(
            model_name='house',
            name='is_furnished',
            field=models.BooleanField(default=False, verbose_name='Is the house furnished?'),
        ),
        migrations.AddField(
            model_name='house',
            name='is_in_quiet_area',
            field=models.BooleanField(default=False, verbose_name='Is in Quiet Area?'),
        ),
        migrations.AddField(
            model_name='house',
            name='is_modern_design',
            field=models.BooleanField(default=False, verbose_name='Is Modern Design?'),
        ),
        migrations.AddField(
            model_name='house',
            name='is_near_commercial_center',
            field=models.BooleanField(default=False, verbose_name='Is Near Commercial Center?'),
        ),
        migrations.AddField(
            model_name='house',
            name='is_near_hospital',
            field=models.BooleanField(default=False, verbose_name='Is Near Hospital?'),
        ),
        migrations.AddField(
            model_name='house',
            name='is_near_ocean_river_lake',
            field=models.BooleanField(default=False, verbose_name='Is Near Ocean/River/Lake?'),
        ),
        migrations.AddField(
            model_name='house',
            name='is_near_pollution_sites',
            field=models.BooleanField(default=False, verbose_name='Is Near Pollution Sites?'),
        ),
        migrations.AddField(
            model_name='house',
            name='is_near_schools',
            field=models.BooleanField(default=False, verbose_name='Is Near Schools?'),
        ),
        migrations.AddField(
            model_name='house',
            name='is_smart_home',
            field=models.BooleanField(default=False, verbose_name='Is Smart Home?'),
        ),
        migrations.AddField(
            model_name='house',
            name='rent_includes_other_services',
            field=models.BooleanField(default=False, verbose_name='Rent Includes Other Services?'),
        ),
        migrations.AddField(
            model_name='house',
            name='was_stayed_by_celebrity',
            field=models.BooleanField(default=False, verbose_name='Was Stayed by Celebrity?'),
        ),
    ]
