# Generated by Django 5.1.3 on 2024-12-27 15:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0027_house_is_rented_as_whole_house_rent_for_whole_house'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], default='photo', max_length=10, verbose_name='Update Type')),
                ('update_file', models.FileField(upload_to='house_updates/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'mp4', 'mov', 'avi'])], verbose_name='Update File (Photo/Video)')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Caption (Optional)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date/Time of Update')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='owners.house', verbose_name='House')),
            ],
        ),
    ]
