# Generated by Django 5.1.3 on 2024-12-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0028_houseupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='is_family_friendly',
            field=models.BooleanField(default=False, verbose_name='Is family friendly?'),
        ),
    ]
