# Generated by Django 5.1.3 on 2024-12-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0029_house_is_family_friendly'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Is the house new?'),
        ),
    ]
