# Generated by Django 5.1.3 on 2024-12-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0031_house_is_pet_friendly'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='has_discount',
            field=models.BooleanField(default=False, verbose_name='Has discount?'),
        ),
    ]
