# Generated by Django 5.1.3 on 2024-12-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0032_house_has_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='is_luxury',
            field=models.BooleanField(default=False, verbose_name='Is Luxury?'),
        ),
    ]
