# Generated by Django 5.1.3 on 2024-12-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0033_house_is_luxury'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='has_scenic_view',
            field=models.BooleanField(default=False, verbose_name='Has scenic view?'),
        ),
    ]
