# Generated by Django 5.1.3 on 2024-12-27 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0034_house_has_scenic_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='is_short_term',
            field=models.BooleanField(default=False, verbose_name='Allows short term payments?'),
        ),
    ]
