# Generated by Django 5.1.3 on 2024-12-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='client_profiles/', verbose_name='Profile Picture'),
        ),
        migrations.AddField(
            model_name='propertyowner',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='property_owner_profiles/', verbose_name='Profile Picture'),
        ),
    ]
