# Generated by Django 5.1.3 on 2024-12-08 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0019_remove_bookingrule_payment_method_and_more'),
        ('settings', '0004_alter_payment_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(auto_now_add=True, help_text='The date on which the booking is created.', verbose_name='Booking Date')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='The total amount to be paid for this booking.', max_digits=10, verbose_name='Total Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this booking was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this booking was last updated.', verbose_name='Updated At')),
                ('payment_method', models.ForeignKey(blank=True, help_text='The payment method selected for this booking.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='settings.payment', verbose_name='Payment Method')),
                ('room', models.ForeignKey(help_text='The room being booked.', on_delete=django.db.models.deletion.CASCADE, related_name='bookings_from_booking_app', to='owners.room', verbose_name='Room')),
                ('user', models.ForeignKey(help_text='The user who made this booking.', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
