# Generated by Django 5.1.3 on 2024-12-08 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_client_profile_picture_propertyowner_profile_picture'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(default=0, help_text='The client who made this booking.', on_delete=django.db.models.deletion.CASCADE, related_name='bookings_from_booking_app', to='accounts.client', verbose_name='Client'),
            preserve_default=False,
        ),
    ]
