# Generated by Django 5.1.3 on 2024-12-09 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_client_profile_picture_propertyowner_profile_picture'),
        ('booking', '0002_remove_booking_user_booking_client'),
        ('owners', '0019_remove_bookingrule_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the bill (e.g., Water Bill, Maintenance Fee, etc.).', max_length=255, verbose_name='Bill Title')),
                ('description', models.TextField(blank=True, help_text='Details or description of the bill.', null=True, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount to be paid for this bill.', max_digits=10, verbose_name='Amount')),
                ('due_date', models.DateField(help_text='The date by which the bill should be paid.', verbose_name='Due Date')),
                ('validity_period', models.CharField(help_text="The time this bill will be valid (e.g., 'One Month', 'Three Months').", max_length=50, verbose_name='Validity Period')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this bill was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this bill was last updated.', verbose_name='Updated At')),
                ('house', models.ForeignKey(help_text='The house this bill is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='owners.house', verbose_name='House')),
                ('property_owner', models.ForeignKey(help_text='The property owner creating this bill.', on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='accounts.propertyowner', verbose_name='Property Owner')),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
                'ordering': ['-created_at'],
            },
        ),
    ]
