# Generated by Django 5.1.3 on 2024-12-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Optional payment number for the bill (e.g., account or invoice number).', max_length=20, null=True, verbose_name='Reference Number'),
        ),
    ]
