# Generated by Django 5.1.3 on 2024-12-09 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_bill_reference_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='due_date',
        ),
    ]
