# Generated by Django 5.1.3 on 2024-12-09 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_client_profile_picture_propertyowner_profile_picture'),
        ('booking', '0005_remove_bill_due_date'),
        ('owners', '0019_remove_bookingrule_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_liked', models.BooleanField(default=False, help_text='Indicates if the client liked this house.', verbose_name='Is Liked')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this record was created.', verbose_name='Created At')),
                ('client', models.ForeignKey(help_text='The client who liked or disliked the house.', on_delete=django.db.models.deletion.CASCADE, related_name='liked_houses', to='accounts.client', verbose_name='Client')),
                ('house', models.ForeignKey(help_text='The house that is liked or disliked.', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='owners.house', verbose_name='House')),
            ],
            options={
                'verbose_name': 'House Like',
                'verbose_name_plural': 'House Likes',
                'unique_together': {('client', 'house')},
            },
        ),
    ]
