# Generated by Django 5.1.3 on 2024-12-09 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_client_profile_picture_propertyowner_profile_picture'),
        ('booking', '0006_houselike'),
        ('owners', '0019_remove_bookingrule_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='The text of the comment made by the client.', verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this comment was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this comment was last updated.', verbose_name='Updated At')),
                ('client', models.ForeignKey(help_text='The client who made this comment on the room.', on_delete=django.db.models.deletion.CASCADE, related_name='room_comments', to='accounts.client', verbose_name='Client')),
                ('room', models.ForeignKey(help_text='The room this comment is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='owners.room', verbose_name='Room')),
            ],
            options={
                'verbose_name': 'Room Comment',
                'verbose_name_plural': 'Room Comments',
                'ordering': ['-created_at'],
            },
        ),
    ]
