# Generated by Django 5.1.3 on 2024-12-09 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_client_profile_picture_propertyowner_profile_picture'),
        ('booking', '0007_roomcomment'),
        ('owners', '0019_remove_bookingrule_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(help_text='The text content of the comment made by the client.', verbose_name='Comment Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this comment was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this comment was last updated.', verbose_name='Updated At')),
                ('client', models.ForeignKey(help_text='The client who made the comment.', on_delete=django.db.models.deletion.CASCADE, related_name='house_comments', to='accounts.client', verbose_name='Client')),
                ('house', models.ForeignKey(help_text='The house this comment is related to.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='owners.house', verbose_name='House')),
            ],
            options={
                'verbose_name': 'House Comment',
                'verbose_name_plural': 'House Comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='RoomComment',
        ),
    ]
