# Generated by Django 5.1.3 on 2024-12-06 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_client_profile_picture_propertyowner_profile_picture'),
        ('owners', '0013_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(choices=[('Bank Transfer', 'Bank Transfer'), ('Mobile Money', 'Mobile Money'), ('Credit Card', 'Credit Card'), ('PayPal', 'PayPal'), ('Other', 'Other')], help_text='Select the type of payment method (e.g., Bank Transfer, Mobile Money).', max_length=50, verbose_name='Payment Method')),
                ('provider', models.CharField(choices=[('M-Pesa', 'M-Pesa'), ('Yas', 'Yas'), ('Halopesa', 'Halopesa'), ('Airtel Money', 'Airtel Money'), ('Azam Pesa', 'Azam Pesa'), ('CRDB Bank', 'CRDB Bank'), ('NMB Bank', 'NMB Bank'), ('Exim Bank', 'Exim Bank'), ('PayPal', 'PayPal'), ('Stripe', 'Stripe'), ('Other', 'Other')], help_text='Select the payment provider (e.g., M-Pesa, Yas, CRDB Bank).', max_length=50, verbose_name='Payment Provider')),
                ('account_details', models.TextField(help_text='Provide account details for this payment method (e.g., account number, phone number).', verbose_name='Account Details')),
                ('instructions', models.TextField(blank=True, help_text='Additional instructions for using this payment method.', null=True, verbose_name='Instructions')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', help_text='Set the status of this payment method (Active or Inactive).', max_length=10, verbose_name='Status')),
                ('currency', models.CharField(default='TZS', help_text='The currency supported by this payment method (e.g., TZS, USD).', max_length=10, verbose_name='Currency')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this payment method was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this payment method was last updated.', verbose_name='Updated At')),
                ('house', models.ForeignKey(blank=True, help_text="The house this payment method is specific to. Leave blank if it's for all houses.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='owners.house', verbose_name='House')),
                ('property_owner', models.ForeignKey(help_text='The property owner associated with this payment method.', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.propertyowner', verbose_name='Property Owner')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
            },
        ),
    ]
