# Generated by Django 5.1.3 on 2024-12-07 11:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_client_profile_picture_propertyowner_profile_picture'),
        ('owners', '0013_agent'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time when the booking was made.', verbose_name='Booking Date')),
                ('check_in_date', models.DateField(help_text='The date when the client plans to check in.', verbose_name='Check-In Date')),
                ('check_out_date', models.DateField(help_text='The date when the client plans to check out.', verbose_name='Check-Out Date')),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Pending', help_text='The status of the payment for this booking.', max_length=15, verbose_name='Payment Status')),
                ('total_cost', models.DecimalField(decimal_places=2, help_text='The total cost for the booking.', max_digits=10, verbose_name='Total Cost')),
                ('special_requests', models.TextField(blank=True, help_text='Any special requests or instructions from the client.', null=True, verbose_name='Special Requests')),
                ('status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending')], default='Pending', help_text='The current status of the booking.', max_length=10, verbose_name='Booking Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('client', models.ForeignKey(help_text='The client making the booking.', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='accounts.client', verbose_name='Client')),
                ('room', models.ForeignKey(help_text='The room being booked.', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='owners.room', verbose_name='Room')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
