# Generated by Django 5.1.3 on 2024-12-08 04:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='number',
            field=models.CharField(default='+255', help_text='Enter a valid mobile number starting with +255 followed by 9 digits.', max_length=13, validators=[django.core.validators.RegexValidator(message='Invalid number. The format should be +255 followed by 9 digits.', regex='^\\+255\\d{9}$')], verbose_name='Recipient Number'),
        ),
        migrations.AddField(
            model_name='payment',
            name='recipient_name',
            field=models.CharField(default=0, help_text='The name that will be displayed during payments to the above number.', max_length=100, verbose_name='Recipient Name'),
            preserve_default=False,
        ),
    ]
