# Generated by Django 5.1.3 on 2024-12-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_payment_number_payment_recipient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='number',
            field=models.CharField(help_text='Enter a valid mobile number that will receive the payment.', max_length=20, verbose_name='Recipient Number'),
        ),
    ]
