# Generated by Django 5.1.3 on 2024-12-13 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_ward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streets', to='settings.ward')),
            ],
        ),
    ]
