# Generated by Django 5.1.3 on 2024-12-16 18:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0024_remove_house_house_photo_1_and_more'),
        ('settings', '0009_street'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude value between -90 and 90 degrees.', max_digits=9, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude value between -180 and 180 degrees.', max_digits=9, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, help_text='Optional altitude in meters.', max_digits=7, null=True)),
                ('house', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='owners.house', verbose_name='Related House')),
            ],
            options={
                'verbose_name': 'House Location',
                'verbose_name_plural': 'House Locations',
            },
        ),
    ]
